services:
    maggie:
        image: maggie:latest
        command: sh -c "python3 maggie.py"
        build:
            context: .
            dockerfile: Dockerfile-maggie
        volumes:
            - .:/app
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          capabilities: [gpu]
                          device_ids: ['0']
